import os
import sys

project_root = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "..")
)

if project_root not in sys.path:
    sys.path.insert(0, project_root)


from langchain_core.messages import HumanMessage
from src.services.agentic_ai.graph import graph


def main():

    print("Autonomous AI Inventory")


    while True:

        user_input = input(
            "Enter Product Name (or Type Exit): "
        )


        if user_input.strip().lower() in {
            "quit",
            "exit",
            "bye"
        }:
            print("Exiting Application")
            break


        state = {

            # User input
            "message": [
                HumanMessage(content=user_input)
            ],


            # Inventory Agent
            "inventory": {},

            "all_dates_inventory": [],

            "next_day_inventory": {},


            # Demand Agent
            "demand": {},


            # Risk Agent
            "risk": "",


            # NEW: Generated by Inventory Agent using Gemini
            "policy_query": "",


            # RAG Agent output
            "policy": {},


            # Recommendation Agent output
            "recommendation": "",


            # Error handling
            "error": None,
        }


        try:

            result = graph.invoke(state)


            if result.get("error"):

                print(
                    f"\nError: {result['error']}"
                )

            else:

                print(
                    "\n===== FINAL RECOMMENDATION ====="
                )

                print(
                    result.get(
                        "recommendation",
                        "No recommendation generated."
                    )
                )


                # Debug outputs
                print(
                    "\n===== DEBUG ====="
                )

                print(
                    "Generated Query:",
                    result.get("policy_query")
                )

                print(
                    "Retrieved Policy:",
                    result.get("policy")
                )


        except Exception as e:

            print(
                f"\nUnexpected Error: {e}"
            )


if __name__ == "__main__":
    main()