from src.services.agentic_ai.state import State
from src.services.rag_policy.search import search_policy


def rag_agent(state: State):

    # Stop if previous agent failed
    if state.get("error"):
        return state

    inventory = state.get("inventory", {})

    # Query generated by Inventory Agent
    query = state.get("policy_query")

    if not query:
        state["error"] = "Policy query not found."
        state["policy"] = "No policy found."
        return state

    try:

        # Retrieve the most relevant policies
        response = search_policy(
            query=query,
            k=2
        )

        policy = "No policy found."

        if response["status"] == "success" and response["count"] > 0:

            results = response["results"]

            # Use the highest-ranked policy returned by semantic search
            policy = results[0]["content"]

        print(f"[RAG] Query  : {query}")
        print(f"[RAG] Policy : {policy}")

        state["policy"] = policy
        inventory["policy"] = policy

        # Update latest inventory history
        history = state.get("all_dates_inventory", [])

        if history:
            history[-1]["policy"] = policy

        # Update next-day prediction
        next_day = state.get("next_day_inventory")

        if isinstance(next_day, dict):
            next_day["policy"] = policy

    except Exception as e:

        print(f"[RAG ERROR] {e}")

        state["policy"] = "No policy found."
        inventory["policy"] = "No policy found."
        state["error"] = f"RAG Error: {e}"

    return state