from src.services.agentic_ai.state import State
from src.services.rag_policy.search import search_policy


def rag_agent(state: State):

    # Stop if previous agent failed
    if state.get("error"):
        return state

    inventory = state.get("inventory", {})

    # Query generated by Inventory Agent (fallback to product name if missing)
    query = state.get("policy_query")

    if not query:
        product_name = inventory.get("product_name", "product")
        query = f"Inventory management policy for {product_name}"
        print(f"[RAG] policy_query was empty, using fallback: {query}")

    try:

        # Hybrid Search (SQLite + ChromaDB)
        response = search_policy(query,k=1)

        if response["status"] != "success":
            print(f"[RAG Warning] {response['message']}")
            state["policy"] = "No policy found."
            inventory["policy"] = "No policy found."
            return state

        result = response["result"]
        policy = result["content"]

        print(f"[RAG] Semantic Query : {query}")
        print(f"[RAG] Policy ID      : {result['policy_id']}")
        print(f"[RAG] Policy Type    : {result['policy_type']}")
        print(f"[RAG] Product        : {result['product']}")
        print(f"[RAG] Retrieved Policy:\n{policy}")

        state["policy"] = policy
        inventory["policy"] = policy

        # Update inventory history
        history = state.get("all_dates_inventory", [])

        if history:
            history[-1]["policy"] = policy

        # Update next-day prediction
        next_day = state.get("next_day_inventory")

        if isinstance(next_day, dict):
            next_day["policy"] = policy

    except Exception as e:

        print(f"[RAG ERROR] {e}")

        state["policy"] = "No policy found."
        inventory["policy"] = "No policy found."

    return state