try:
    from .vector_db import load_vector_db
except ImportError:
    from vector_db import load_vector_db


def search_policy(query: str, k: int = 2) -> str:
    """
    Retrieve the top-k most similar policy chunks and return them as a concatenated string.

    Args:
        query (str): Search query generated by another module.
        k (int): Number of similar policy chunks.

    Returns:
        str: Concatenated content of retrieved policies or a fallback string.
    """
    try:
        if not query or not query.strip():
            return "No policy found."

        vector_db = load_vector_db()

        if vector_db is None:
            return "No policy found. (Unable to load Vector Database)"

        results = vector_db.similarity_search(
            query=query,
            k=k
        )

        if not results:
            return "No policy found."

        retrieved_contents = []
        seen = set()

        for doc in results:
            content = doc.page_content.strip()
            if content in seen:
                continue
            seen.add(content)
            retrieved_contents.append(content)

        if not retrieved_contents:
            return "No policy found."

        return "\n\n".join(retrieved_contents)

    except Exception as e:
        print(f"Error in search_policy: {e}")
        return "No policy found."


if __name__ == "__main__":
    test_query = "Overstock Limit Grapes"
    response = search_policy(
        query=test_query,
        k=2
    )
    print(response)