from src.services.rag_policy.vector_db import load_vector_db


def search_policy(query: str, k: int = 1):
    """
    Semantic Search using ChromaDB.

    Args:
        query (str): Semantic query generated by Gemini.
        k (int): Number of policies to retrieve.

    Returns:
        dict: Retrieved policy details.
    """

    try:

        if not query or not query.strip():
            return {
                "status": "error",
                "message": "Query cannot be empty."
            }

        vector_db = load_vector_db()

        if vector_db is None:
            return {
                "status": "error",
                "message": "Unable to load Vector Database."
            }

        results = vector_db.similarity_search(
            query=query,
            k=k
        )

        if not results:
            return {
                "status": "error",
                "message": "No matching policy found."
            }

        doc = results[0]

        return {
            "status": "success",
            "result": {
                "policy_id": doc.metadata.get("policy_id", "N/A"),
                "policy_type": doc.metadata.get("policy_type", "N/A"),
                "product": doc.metadata.get("product", "N/A"),
                "page": doc.metadata.get("page", "N/A"),
                "source": doc.metadata.get("source", "N/A"),
                "content": doc.page_content
            }
        }

    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }


if __name__ == "__main__":

    test_query = "Inventory stockout handling policy"

    response = search_policy(test_query)

    print(response)