from src.services.rag_policy.vector_db import load_vector_db



def search_policy(query, k=2):
    """
    Retrieve the top-k most similar policy chunks.

    Args:
        query (str): Search query generated by another module.
        k (int): Number of similar policy chunks.

    Returns:
        dict: Search results.
    """

    try:


        if not query or not query.strip():
            return {
                "status": "error",
                "message": "Query cannot be empty."
            }

        vector_db = load_vector_db()

        if vector_db is None:
            return {
                "status": "error",
                "message": "Unable to load Vector Database."
            }

        results = vector_db.similarity_search(
            query=query,
            k=k
        )

        if not results:
            return {
                "status": "success",
                "count": 0,
                "results": []
            }

        retrieved_policies = []

        seen = set()

        for doc in results:

            key = (
                doc.metadata.get("policy_id"),
                doc.page_content
            )

            if key in seen:
                continue

            seen.add(key)

            retrieved_policies.append({

                "policy_id": doc.metadata.get("policy_id", "N/A"),

                "policy_type": doc.metadata.get("policy_type", "N/A"),

                "product": doc.metadata.get("product", "N/A"),

                "page": doc.metadata.get("page", "N/A"),

                "source": doc.metadata.get("source", "N/A"),

                "content": doc.page_content

            })

        return {
            "status": "success",
            "count": len(retrieved_policies),
            "results": retrieved_policies
        }

    except Exception as e:

        return {
            "status": "error",
            "message": str(e)
        }


if __name__ == "__main__":

    test_query = "Overstock Limit Grapes"
    answer=search_policy(test_query)


    print("\nRetrieved Policy:")
    print(answer)

    response = search_policy(
        query=test_query,
        k=2
    )

    print(response)

